# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI
env:
  NODE_VERSION: "14.x"

on: [push]

jobs:
  lint:
    name: ✅ Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{env.NODE_VERSION}}
      - run: npm ci
      - run: npm run lint --if-present
  test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{env.NODE_VERSION}}
      - run: npm ci
      - run: npm test --if-present
  typeCheck:
    name: Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{env.NODE_VERSION}}
      - run: npm ci
      - run: npm run typeCheck --if-present
  deploy:
    needs: [typeCheck, test, lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{env.NODE_VERSION}}
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm run gh-build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          external_repository: allen-cell-animated/website-3d-cell-viewer-release
          deploy_key: ${{ secrets.SSH_PRIVATE_KEY }}
          publish_dir: ./imageviewer
          tag_name: test-deploy-${{ github.ref_name }}
          tag_message: "TEST Deployment to website-3d-cell-viewer-release ${{ github.ref_name }}"
